### ISSUE TITLE
How to get an image with layer blending mode? 

### ISSUE THREAD

**Issue by ironxu** [alco/psdump#7]
this is my code

> psd_context* context = NULL;
> psd_status status = psd_image_load(&context, "D:\\test.psd");
> psd_short layer_count = context->layer_count;
> for (size_t i = 0; i < layer_count; i++)
> {
> 	psd_layer_record record = context->layer_records[i];
> 	unsigned int *image_data_ = NULL;
> 	unsigned long image_data_length_ = NULL;
> 	unsigned long num_bytes = record.width * record.height * 4;
> 	unsigned int *buf = record.image_data;
> 
> 	image_data_ = new unsigned int[num_bytes];
> 	image_data_length_ = num_bytes / 4;
> 	memcpy(image_data_, buf, num_bytes);
>  	/*write to file code*/
>  	/*...*/
> }
> psd_image_free(context);
> 

I use '**psd_image_blend**', but it doesn't seem to work. Can you tell me how to get a blending layer?

**Comment by alco** [comment]
@ironxu I'm sorry but I don't know the answer to that.

**Comment by ironxu** [comment]
> @ironxu I'm sorry but I don't know the answer to that.
Thank you for your answer.
Maybe I didn't describe it correctly.
I want to export an image that has a layer style.
Such as
![la_10](https://user-images.githubusercontent.com/38871684/48888318-4a49da00-ee6d-11e8-8735-da90e173a032.png)
It looks like it needs to render itself.

**Comment by alco** [comment]
I haven't worked with PSDs for a long while so I'm afraid I can't help you. I can only suggest asking on https://stackoverflow.com/.
